{
 "title": "Dashboard Actividad 22 - demo-app",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \r\n  sum by (le) (\r\n    rate(http_server_duration_milliseconds_bucket{exported_job=\"demo-app\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{exported_job=\"demo-app\", status_code=~\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{exported_job=\"demo-app\"}[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}